### ISSUE TITLE
Consumed memory not cleanup rigth after usage

### ISSUE THREAD

**Issue by Wijnand** [xerions/mariaex#96]
There is a really easy reproducable memory leak in mariaex.
I have a table with 3000 rows, only a simple string column.
   {:ok, _} = Mariaex.Connection.query(pid, "SELECT name FROM test")
Each time I run this line memory jumps with around 60Mb

**Comment by ericmj** [comment]
Is the memory ever reclaimed? What do you do with the names after they are fetched?

Try calling `:binary.copy/1` on every name returned and see if that fixes the memory issue.

**Comment by Wijnand** [comment]
It is never reclaimed, in the example given I do nothing with the result.

**Comment by Wijnand** [comment]
Example code: https://github.com/Wijnand/mariaex_leak

**Comment by ericmj** [comment]
Initially I thought it was related to this issue https://github.com/ericmj/postgrex/issues/167 but since you never hold a reference to the returned binaries you can't obviously copy them.

I think what's going in here is that mariaex is doing something inefficient binaries like concatenating them all before decoding. I believe @maxim also saw memory usage that was way more than he was fetching from the database.

**Comment by stephankaag** [comment]
Reproducible. This is not good.

**Comment by maxim** [comment]
@Wijnand thanks for the sample code, was gonna throw it together too. As a temporary workaround, doing `:binary.copy` on the string will likely clear up the RAM (it did in my case).

**Comment by ericmj** [comment]
Right, if you run it in your shell you are going to store references to the binaries and in that case `:binary.copy/1` will help. But if the shell has already stored the values (for the `v/1` helper) then you probably have to respawn the shell to clear the references.

**Comment by Wijnand** [comment]
But this test case has nothing to do with the shell right? Mariaex is leaking and should be fixed.

**Comment by ericmj** [comment]
Yes, I am strictly talking about the workaround. And mariaex isn't strictly leaking, you are holding onto the binaries so they can't be garbage collected. It's probably being inefficient with the binaries though.

**Comment by Wijnand** [comment]
Doing the exact same thing with mysqlex does not leak.
And  how am I holding onto the binaries in the test case I provided?

**Comment by liveforeverx** [comment]
It is not memory-leak, I've run it 10000 times and memory doesn't grow constantly.

**Comment by liveforeverx** [comment]
I've renamed it to something, what describes the problem more, first part is fixed now on master. It has hold references to the last query, now it doesn't hold, and by explicit :erlang.garbage_collect the memory is cleaned, that means that there are no more references to binary result.

**Comment by liveforeverx** [comment]
But, it has definitely to have something with coping of binaries between 2 processes, because the vm handles Refc binaries different, if it referenced from one process or from different places (like ets/send per messages).

@maxim, can you test please, the `db_connection` branch, if the memory is overconsumed here too without binary copy??

**Comment by liveforeverx** [comment]
So, I've released `v0.6.4`, which doesn't hold references to last query, due to the fact, that mariaex works in active mode and not in passive, there is more manipulation and another kind of manipulation, which may be less efficient(for example save list of rows in a map state, where it can be avoided in passive mode), but I've tested with upcoming version, which use db_connection, it doesn't have the same problem, due to the fact, that it isn't memory leak and fixed in upcoming version, I do not think, that it is a value to investigate it further.

**Comment by Wijnand** [comment]
Ok, thank you very much! I will use the 0.6.4 version for now and switch to the upcoming version as soon as feasible.

**Comment by Wijnand** [comment]
0.6.4 does not fix the issue by the way, still reproducible in my silly test app that discards the results immediately.

**Comment by liveforeverx** [comment]
@Wijnand yes, because beam VM garbage collect Refc binaries lazy in some circumstances. In case, where it discarded immediately, it doesn't means, that VM garbage collect it immediately too. If you will do afterward (force garbage collection):

```elixir
Enum.each([p, self], &:erlang.garbage_collect/1)
```

The memory is reclaimed. It happens, because connection have binaries and sends it to calling process, and both processes have references to results (that means, 2 references to binaries), and self in a case, it is immediately discarded.

The only question for me, why it uses 60 mb... (what I have overseen)

Upcoming version, is in branch `db_connection` doesn't have the same effect.

**Comment by Wijnand** [comment]
I can confirm that, the db_connection branch does not have this issue.

**Comment by liveforeverx** [comment]
As it is fixed on master now, close it.

**Comment by ericmj** [comment]
I think you should why so much large binaries are generated. Using 60mb of memory does not make sense. You can try compiling with bin_opt_info.

**Comment by liveforeverx** [comment]
@ericmj: In master version, there is no more large binaries generated, but I can investigate previous version, why it was so.

**Comment by liveforeverx** [comment]
@ericmj : Started to analyse, try to compare 2 versions, which consume 60MB and on master, which consumes 1000 times less on master, nothing changes with warnings.

**Comment by liveforeverx** [comment]
It doesn't point to anything, but I can optimize code according to warnings and check, if it changes the performance.

**Comment by liveforeverx** [comment]
@ericmj I found the problem in old version

**Comment by liveforeverx** [comment]
Place, where it has copied the binary: https://github.com/xerions/mariaex/blob/v0.6/lib/mariaex/connection.ex#L284

Version v0.6.5 released.
