### ISSUE TITLE
Connection Failure with new Phoenix Project

### ISSUE THREAD

**Issue by paulgithub** [xerions/mariaex#99]
The following error can be easily reproduced by creating a new Phoenix project:

$ mix phoenix.new tmp_app --database mysql

Then adding a new model with tests followed by migration, etc. and then running tests:

$ mix test test/models

The mix.exs uses the defaults produced by the mix phoenix.new command above. The only changes are to the config/test.exs file for the database connection, updated username, password, database.

The error can also be created on an existing Phoenix project by updating mariaex from 0.6.x to 0.7.0.

The issue in other words is with the new version 0.7.0.

Here is the error:

```
11:33:55.040 [error] GenServer TmpApp.Repo.Pool terminating
** (Protocol.UndefinedError) protocol Enumerable not implemented for nil
    (elixir) lib/enum.ex:1: Enumerable.impl_for!/1
    (elixir) lib/enum.ex:116: Enumerable.reduce/3
    (elixir) lib/enum.ex:1486: Enum.reduce/3
    (mariaex) lib/mariaex/query.ex:135: DBConnection.Query.Mariaex.Query.decode/3
    (db_connection) lib/db_connection.ex:423: DBConnection.query/4
    (mariaex) lib/mariaex.ex:138: Mariaex.query/4
    (ecto) lib/ecto/adapters/mysql/connection.ex:25: Ecto.Adapters.MySQL.Connection.query/4
    (stdlib) timer.erl:197: :timer.tc/3
** (exit) exited in: GenServer.call(TmpApp.Repo.Pool, {:query, :begin, &TmpApp.Repo.log/1, [timeout: 15000]}, 5000)
    ** (EXIT) an exception was raised:
        ** (Protocol.UndefinedError) protocol Enumerable not implemented for nil
            (elixir) lib/enum.ex:1: Enumerable.impl_for!/1
            (elixir) lib/enum.ex:116: Enumerable.reduce/3
            (elixir) lib/enum.ex:1486: Enum.reduce/3
            (mariaex) lib/mariaex/query.ex:135: DBConnection.Query.Mariaex.Query.decode/3
            (db_connection) lib/db_connection.ex:423: DBConnection.query/4
            (mariaex) lib/mariaex.ex:138: Mariaex.query/4
            (ecto) lib/ecto/adapters/mysql/connection.ex:25: Ecto.Adapters.MySQL.Connection.query/4
            (stdlib) timer.erl:197: :timer.tc/3
    (elixir) lib/gen_server.ex:564: GenServer.call/3
    (ecto) lib/ecto/adapters/sql.ex:407: Ecto.Adapters.SQL.test_transaction/5
    (elixir) lib/code.ex:363: Code.require_file/2
    (elixir) lib/enum.ex:604: Enum."-each/2-lists^foreach/1-0-"/2
    (elixir) lib/enum.ex:604: Enum.each/2
```

**Comment by cbarratt** [comment]
I'm currently receiving the same error, just upgraded from 0.6 to 0.7

**Comment by somlor** [comment]
Same issue. Downgrading to `0.6.5` fixed this. Let me know if you need any more information or help of any kind.

**Comment by reneklacan** [comment]
Same issue here, downgrading helped

**Comment by liveforeverx** [comment]
Thanks for reporting, will check it.

**Comment by liveforeverx** [comment]
Fixed with `0.7.1`

**Comment by reneklacan** [comment]
👏

**Comment by matteosister** [comment]
I still have this same problem, even with version 0.7.1 :disappointed:

**Comment by liveforeverx** [comment]
Hi!

@matteosister How could I reproduce it?

**Comment by matteosister** [comment]
I just created a new project with mix phoenix.new --database mysql, than I created a model with mix phoenix.gen.model, and ```mix test``` gives this error. I used docker-compose, mysql is on 5.7.

If you want I can start a new project and share the repo...

**Comment by liveforeverx** [comment]
@matteosister Seems, like it hasn't recompiled by me. I'll release new version today.

**Comment by liveforeverx** [comment]
@matteosister now it is fixed and released.

**Comment by matteosister** [comment]
@liveforeverx many thanks! :heart:
